### PR TITLE
Bugfix for htgettoken URL not showing up

### PR DESCRIPTION
**Pull request by shreyb**
This just makes sure to print the stdout from htgettoken, since under normal conditions, it's not that much output.

More importantly, the user needs to see the authentication URL if they're getting the token for the first time

### CODE REVIEW

**Comment by shreyb** [comment]
Closes #110

**Review by marcmengel — COMMENTED** [review]
This says send output to stderr in the comments but does the opposite... 1>&2 is sending stdout to stderr...

**Comment by shreyb** [comment]
Thanks for catching that @marcmengel .  It's now fixed.

**Comment by retzkek** [comment]
Wait, no shouldn't the code have been changed to match the comment? Or maybe I don't understand, so why do we want to redirect either stdout or stderr instead of passing them both through respectively?

**Comment by shreyb** [comment]
The code as written was doing the right thing in terms of passing stderr to stdout.  The comment in the code however, was wrong, and said that output was getting passed to stderr.  So this last commit was just changing that comment so that it matched what the code was doing.  We want everything to go to stdout, since `os.system()` sends all stdout to the interpreter's (user's) stdout.

**Comment by shreyb** [comment]
Talked to @retzkek offline.  He's right that `os.system()` already dumps everything to the interpreter's stdout, so there's no reason for us to do so.  I changed the code to reflect this.

**Review by retzkek — APPROVED** [review]
LGTM

**Pull request merged**
