### PR TITLE
Resolve --singularity-image and --lines with +SingularityImage conflicts

### PR DESCRIPTION
**Pull request by shreyb**
As described in #330 , we establish the following convention here with regards to the `--singularity_image` flag and `--lines` flag with `SingularityImage` specified:

1.    If --singularity-image is specified and is NOT the default, use that.
2.   If --lines is given with a +SingularityImage classad, and that value is not the default, use that.
3.   Else, use the default.

### CODE REVIEW

**Comment by shreyb** [comment]
In draft status until I can run some "integration"-style tests, and maybe even add them to our test suite.

**Comment by shreyb** [comment]
Unit/integration tests, as well as tests described in #330 all pass.

**Review by marcmengel — APPROVED** [review]
Looks good!

**Comment by marcmengel** [comment]
Also tested my DAG cases with --line +SingularityImage=  vs --singularity-image, seems to do the right thing, and warns when it's overriding --lines with --singularity-image.

**Pull request merged**
