### PR TITLE
use INPUT_TAR_DIR_LOCAL for rcds unpacked tar directories, 

### PR DESCRIPTION
**Pull request by marcmengel**
…and wait for the first one to show up

Second pull request on #134 

"This time Rocky, for sure!!!"

### CODE REVIEW

**Review by shreyb — COMMENTED** [review]
Question here:  As a part of this change, are we breaking backward compatibility - in that INPUT_TAR_FILE will no longer work with RCDS?

**Comment by marcmengel** [comment]
Hm.. I thought INPUT_TAR_FILE already didn't work with RCDS...I mean, the tarfile isn't there, just the contents...

**Comment by marcmengel** [comment]
Yes, in the current jobsub code:
https://cdcvs.fnal.gov/redmine/projects/jobsub/repository/revisions/master/entry/lib/groupsettings/JobSettings.py#L1035
if we have a "cid=" in our tar_file_name we set INPUT_TAR_DIR and INPUT_TAR_DIR_LOCAL, otherwise we set INPUT_TAR_FILE and unpack said tarfile.  We don't set both together.

**Comment by shreyb** [comment]
Ah!  Got it.  Great - then this is good to go.

**Review by shreyb — APPROVED** [review]

**Pull request merged**
